<?php

/**
 * @file
 * This is a short description for the file.
 */

use Drupal\user\UserInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\hello_visitor\Event\UserLoggedInEvent;

/**
 * Implements hook_user_login().
 */
function hello_visitor_user_login(UserInterface $account) {
  \Drupal::logger('hello_visitor')->notice('User @name has logged in.', [
    '@name' => $account->getDisplayName(),
  ]);

  // Dispatch the custom event.
  $event = new UserLoggedInEvent($account);
  \Drupal::service('event_dispatcher')->dispatch($event, UserLoggedInEvent::EVENT_NAME);
}

/**
 * This is a comment.
 */
function hello_visitor_user_register_validate(&$form, FormStateInterface $form_state) {
  if ($form_state->getValue('name') === 'hello_visitor') {
    $form_state->setErrorByName('name', t('The username "hello_visitor" is invalid. Please choose a different name.'));
  }
}
